apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-deployment
  template:
    metadata:
      labels:
        app: gateway-deployment
    spec:
      containers:
        - name: gateway-service
          image: gateway-service
          ports:
            - containerPort: 80
